### ISSUE TITLE
请问一下新番的地址怎么办？

### ISSUE THREAD

**Issue by izuolan** [blogwy/BilibiliVideoDownload#1]
这种格式：

`https://bangumi.bilibili.com/anime/6434/play#115310`

另外顺便加上弹幕下载的按钮？谢谢大佬。

**Comment by blogwy** [comment]
我再研究研究，谢谢提醒，我平常不看番剧，还真每想到这个问题

**Comment by blogwy** [comment]
找到方法了，我会尽快添加上

**Comment by izuolan** [comment]
感谢大佬, 视频对应的弹幕文件也可以解析吗? 因为不是Windows, 下视频不能用jj那些.

**Comment by blogwy** [comment]
弹幕下载也找到方法了，明天我会添加上这些功能。今天有点累了！

**Comment by blogwy** [comment]
新番下载现在有点问题，暂时没有添加，已经添加弹幕下载。
