### ISSUE TITLE
还需要自己添加sess  还要定期更换  有点麻烦呢

### ISSUE THREAD

**Issue by lbcake** [blogwy/BilibiliVideoDownload#13]
你可以弄成自动更新 抓取本地http 账户数据

**Comment by blogwy** [comment]
正在写新版本electron + arir2 +ffmpeg 有ui界面，扫码登录b站

**Comment by lbcake** [comment]
> 正在写新版本electron + arir2 +ffmpeg 有ui界面，扫码登录b站

期待哦     那接口是一流的吗？ 下载up主的视频 会带水印不？

**Comment by blogwy** [comment]
水印肯定是会有的

**Comment by lbcake** [comment]
> 水印肯定是会有的

那还有啥搞头啊

**Comment by blogwy** [comment]
2020年一直沉迷游戏中，导致这个项目快荒废了。今年会重新上线一个带GUI界面的版本软件。其实这方面的开源软件很多，有一个很不错的：https://github.com/SigureMo/bilili

**Comment by Lehmaning** [comment]
> 那还有啥搞头啊

水印应该是B站后台和原视频压制在一起的，没法提取吧。
