### ISSUE TITLE
在哪里添加SESSDATA

### ISSUE THREAD

**Issue by orange2008** [blogwy/BilibiliVideoDownload#14]
我在getUrl.js里面没有找到填写的地方啊

**Comment by blogwy** [comment]
base.js

**Comment by blogwy** [comment]
2020年一直沉迷游戏中，导致这个项目快荒废了。今年会重新上线一个带GUI界面的版本软件。其实这方面的开源软件很多，有一个很不错的：https://github.com/SigureMo/bilili
