### ISSUE TITLE
接口返回code -400

### ISSUE THREAD

**Issue by 2292912322** [blogwy/BilibiliVideoDownload#15]
let videoInfo = await rp(`http://api.bilibili.com/view?type=jsonp&appkey=8e9fc618fbd41e28&id=${aid}&page=${pNum}`),

videoinfo = { code: -400, message: 'Request error.', ts: 1584518421 }

**Comment by blogwy** [comment]
2020年一直沉迷游戏中，导致这个项目快荒废了。今年会重新上线一个带GUI界面的版本软件。其实这方面的开源软件很多，有一个很不错的：https://github.com/SigureMo/bilili
