### ISSUE TITLE
Does it support download from "https://www.bilibili.com/bangumi/play/epxxxx"

### ISSUE THREAD

**Issue by AtlasQuan** [blogwy/BilibiliVideoDownload#16]
I think the anime url has been changed to the new format: https://www.bilibili.com/bangumi/play/epxxxx

Is it supported?

**Comment by blogwy** [comment]
2020年一直沉迷游戏中，导致这个项目快荒废了。今年会重新上线一个带GUI界面的版本软件。其实这方面的开源软件很多，有一个很不错的：https://github.com/SigureMo/bilili
