### ISSUE TITLE
请问可以支持1080 的mp4吗

### ISSUE THREAD

**Issue by 5wcx** [blogwy/BilibiliVideoDownload#17]
不合并 原生就有高清的mp4。不知道别人是怎么弄的

**Comment by dengmin** [comment]
mp4高清格式已破解
目前支持 BV AV 多P 且只支持mp4 高清格式
1）原视频清晰度有360P、480P、720P，默认为最高的720P，
2）原视频清晰度有360P、480P、720P、1080P，默认为最高的1080P，
3）原视频清晰度有360P、480P、720P、1080P、1080P+，默认为1080P

欢迎各位体验 http://bilibili.syyhc.com

**Comment by blogwy** [comment]
2020年一直沉迷游戏中，导致这个项目快荒废了。今年会重新上线一个带GUI界面的版本软件。其实这方面的开源软件很多，有一个很不错的：https://github.com/SigureMo/bilili
