### ISSUE TITLE
请问这种情况如何解决？

### ISSUE THREAD

**Issue by HM-plus** [blogwy/BilibiliVideoDownload#18]
![image](https://user-images.githubusercontent.com/66710204/98502854-12244780-228e-11eb-967b-29cda7b5ab3f.png)

**Comment by Kimsome** [comment]
蹲一个答案

**Comment by Z-Y00** [comment]
同样的问题， 改成数字就好了

> 请输入av号...1111
> 这是个单P视频
> 
> [1] 高清1080P
> [2] 获取视频清晰度错误!!!
> [3] 清晰480P
> [4] 流畅360P
> [0] CANCEL
> 
> 选择要下载到清晰度？ [1...4 / 0]: 
> 

> 
> 请输入av号...BV1Mx41147Np
> 这是个单P视频
> (node:12426) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'accept_quality' of undefined

**Comment by Z-Y00** [comment]
@HM-plus  @Kimsome 这里要的是 数字的av 号，或许可以试试这个转换
http://hofuy.cn/tools/bv-av/

**Comment by blogwy** [comment]
2020年一直沉迷游戏中，导致这个项目快荒废了。今年会重新上线一个带GUI界面的版本软件。其实这方面的开源软件很多，有一个很不错的：https://github.com/SigureMo/bilili
