### ISSUE TITLE
UP主很多时，右侧界面占据的空间太大，挡住了左侧界面

### ISSUE THREAD

**Issue by xuejianxianzun** [blogwy/BilibiliVideoDownload#36]
下载这个视频时：
https://www.bilibili.com/video/BV1oP4y1x7zd
界面如图：
![QQ截图20210823103512.jpg](https://i.loli.net/2021/08/23/F4pZkOiMJz9D6RE.jpg)
左侧的下载进度被挡住了。
一个迂回的解决方法是点击其他正常的视频，此时右侧界面是正常大小，所以可以看到下载进度，不过如果能解决这个问题就更好了，谢谢！

**Comment by blogwy** [comment]
最新版已经修复了

**Comment by xuejianxianzun** [comment]
感谢！
