### ISSUE TITLE
[Feature Request] 多P视频下载至单个文件夹内

### ISSUE THREAD

**Issue by breathiness** [blogwy/BilibiliVideoDownload#38]
现在多P视频的文件下载后，会分开在多个文件夹内。使用播放器打开时不能自动加载所有视频。  
能否选择让多P视频下载至单个文件夹内？这样在后续播放时会方便很多。

**Comment by blogwy** [comment]
最新版在设置页面新增了“是否下载到单独文件夹”功能，默认是开启。你关闭后就会下载到你设置的下载路径的根目录。应该可以解决你问题吧。https://github.com/blogwy/BilibiliVideoDownload/releases/tag/v3.1.4

**Comment by breathiness** [comment]
谢谢！解决了
