### ISSUE TITLE
3.1.3版本，我点开设置后，不知道怎么返回主界面

### ISSUE THREAD

**Issue by xuejianxianzun** [blogwy/BilibiliVideoDownload#39]
点开设置后，没有返回按钮，ESC 键也没有反应，点击设置之外的区域也没有反应，不知道怎么办。求助~
系统是 Win10。
![20210922140320.jpg](https://i.loli.net/2021/09/22/PLCFQzyMajsBdHg.jpg)

**Comment by blogwy** [comment]
看你的图片是表单验证没通过，你随便设置一下最大下载数。这是个bug，有时间的话我修复一下吧

**Comment by xuejianxianzun** [comment]
谢谢！

**Comment by blogwy** [comment]
最新版已经修复了这个bug：https://github.com/blogwy/BilibiliVideoDownload/releases/tag/v3.1.4
