### ISSUE TITLE
bug: 安装时安装路径选择D盘根目录,返回再下一步会卡住然后自己关闭

### ISSUE THREAD

**Issue by Weltolk** [blogwy/BilibiliVideoDownload#48]

**Comment by blogwy** [comment]
windows 使用的是NSIS作为安装系统，这个自己关闭是NSIS的逻辑，我暂时没有找到可配置的地方。无法改变

**Comment by Weltolk** [comment]
> windows 使用的是NSIS作为安装系统，这个自己关闭是NSIS的逻辑，我暂时没有找到可配置的地方。无法改变

ok,thanks replay,close
