### ISSUE TITLE
麻烦问下怎么删除全部下载记录

### ISSUE THREAD

**Issue by yuanxinlang** [blogwy/BilibiliVideoDownload#52]
现在删除下载历史记录要一个一个×的点好累，按shift多选也不行，麻烦问下删除全部下载历史记录的按钮在哪？

**Comment by blogwy** [comment]
暂时还没有，下个版本我加一个把。已经有人提过类似的issues：https://github.com/blogwy/BilibiliVideoDownload/issues/49，这个我就关了。
