### ISSUE TITLE
[Feat request] m1 support

### ISSUE THREAD

**Issue by LiuLiujie** [blogwy/BilibiliVideoDownload#57]
Thank you very much for this nice tool!

I notice that in the latest version of this software it still runs under Rosetta 2 in MacOS with M1 chips. And I would like to know if you have a plan to support Apple chips natively. I am not the professional in this area, but I am willing to help you test it and gives you feedback if you want.

FYI. Electron has supported arm64 since v11.0.0 and also ffmpeg since v1.1.0.

**Comment by blogwy** [comment]
Thank you for your idea. I will try

**Comment by blogwy** [comment]
你好，最新版已支持M1。但是由于我没有M1 MAC，无法测试，请帮忙测试一下功能是否正常，谢谢！
https://github.com/blogwy/BilibiliVideoDownload/releases/tag/v3.2.0

**Comment by LiuLiujie** [comment]
你好，测试环境MBP16, M1 Pro, macOS 12.3 Beta3. 首次尝试打开时系统提示错误：“BilibiliVideoDownload” is damaged and can’t be opened. You should move it to the Trash. 根据 Apple 文档猜测是签名问题。使用`sudo xattr -d com.apple.quarantine /Applications/BilibiliVideoDownload.app` 尝试解决，应用可启动但立即提示弹窗主进程 JS 错误 Uncaught Exception: undefined: undefined ,确认后后台驻留但不显示主页面

**Comment by LiuLiujie** [comment]
以上基于 arm64版本，Intel转义版本正常使用

**Comment by blogwy** [comment]
这个问题暂时不知道怎么解决，你如果本地有node环境，可以自己clone代码，打包试试。我现在又打包了一个universal版(在mac x86正常)，你试试这个。

**Comment by LiuLiujie** [comment]
我是 12.3 Beta 的系统，无法本地进行编译，应该是由于以下原因[electron issue ref.](https://github.com/electron-userland/electron-builder/issues/6606)。不清楚运行时涉不涉及 python2 和 3 的版本问题，供参考

**Comment by blogwy** [comment]
我大概猜到主进程奔溃的问题原因了，软件使用了[@ffmpeg-installer/ffmpeg](https://github.com/kribblo/node-ffmpeg-installer)安装ffmpeg，看了一下它源码，是直接用node os库拿当前系统平台和架构去下载对应的ffmpeg二进制包。由于我本地和GitHub Action都是x86架构的macOS，导致打包arm架构的dmg包时候用的是x86平台的ffmpeg二进制包，视频合成时候都是在主进程进行，直接主进程报错。

**Comment by LiuLiujie** [comment]
arm和 universal 均测试了。universal 正常使用，arm 版本使用也正常但签名似乎有点问题。在 Applications 文件夹右键打开也无法打开，会提示损坏，需要手动`sudo xattr -d com.apple.quarantine /Applications/BilibiliVideoDownload.app` 后才可。非常感谢作者的付出!~

**Comment by blogwy** [comment]
> arm和 universal 均测试了。universal 正常使用，arm 版本使用也正常但签名似乎有点问题。在 Applications 文件夹右键打开也无法打开，会提示损坏，需要手动`sudo xattr -d com.apple.quarantine /Applications/BilibiliVideoDownload.app` 后才可。非常感谢作者的付出!~

谢谢测试，签名需要苹果开发者账户，开发者账户还得给apple交199美元，所以我也没有账号。😂
