### ISSUE TITLE
已经登陆了，普通非收费视频，有1080P，却最高只能选择720P

### ISSUE THREAD

**Issue by yyl9510** [blogwy/BilibiliVideoDownload#59]

**Comment by blogwy** [comment]
请先检查软件版本是否死最新版；如果是当前最新版，可否提供一下视频url，我测试了视频、番剧、电影都可以正常解析清晰度的。没有复现你的问题。

**Comment by yyl9510** [comment]
> 请先检查软件版本是否死最新版；如果是当前最新版，可否提供一下视频url，我测试了视频、番剧、电影都可以正常解析清晰度的。没有复现你的问题。

是最新版，这是例子，https://www.bilibili.com/video/BV1PV411774y，有1080P，但是最高只能下载720P

**Comment by blogwy** [comment]
这个问题目前无法解决。只能通过上述方法解决。我暂时找不到接口可以实现一次把所有分集视频信息都请求到。如果一个一个请求不现实

**Comment by yyl9510** [comment]
> 这个问题目前无法解决。只能通过上述方法解决。我暂时找不到接口可以实现一次把所有分集视频信息都请求到。如果一个一个请求不现实

ok
