### ISSUE TITLE
web版本

### ISSUE THREAD

**Issue by LawssssCat** [blogwy/BilibiliVideoDownload#64]
能不能开发个web服务器版本的客户端，浏览器访问某个端口进入BilibiliVideoDownload下载界面？

**Comment by blogwy** [comment]
抱歉，不考虑，web版的话需要服务器，开发api。而且还会有不可控风险

**Comment by fantasyjqc** [comment]
> 抱歉，不考虑，web版的话需要服务器，开发api。而且还会有不可控风险

上面的小伙伴估计说的是self host版本，docker那种，在nas上起一个服务，然后可以在web上下载。很期待这样的版本，不知道大佬是否考虑开发。

**Comment by SpinningK** [comment]
同求self host版本
