### ISSUE TITLE
Mac系统下出现下载失败

### ISSUE THREAD

**Issue by zsbai** [blogwy/BilibiliVideoDownload#65]
有大会员，在macOS12.2系统下，软件版本为3.2.0，intel版本，单个视频文件登陆后不伦分辨率为多少，在最后均出现下载失败
<img width="804" alt="image" src="https://user-images.githubusercontent.com/62942942/158336652-3fe7c9c7-ca39-4b78-8a34-beb71d23edc6.png">
试了几个视频没有一个下载成功的...

**Comment by blogwy** [comment]
我测试了几个视频没问题，不管是大会员还是非会员视频都可以。然后你这个[视频](https://www.bilibili.com/video/BV1ZT4y1U7js?spm_id_from=333.337.search-card.all.click)我第一次下载失败了，具体原因是timeout，第二次下载成功。
我之前是遇到过由于DNS问题，导致下载一直失败。换了个网络或者重新设置DNS好了，你可以试试

**Comment by yvonne66999** [comment]
我也遇到了同样的问题 昨天晚上开始都下载不了 https://www.bilibili.com/video/BV1SU4y1o7oL?spm_id_from=333.788.top_right_bar_window_history.content.click （👈比如这个）

**Comment by zsbai** [comment]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/62942942/158563159-eecb94c8-b006-429a-97bd-2b93229bb77b.png">
我依旧是下载失败，经测试不是网络问题，而且问题时出现下载后的，下载中--音频下载中--视频合成中..---下载失败，大概是这么个流程，所以其实是下载好了的，我没找到日志文件在哪里所以提供不了日志😂 进度在到视频合成时几乎是秒变下载失败

**Comment by yvonne66999** [comment]
> 出现

我和你的问题是一样的，“视频合成中”之后才显示失败。此外文件夹里只有封面图，没有视频。另外我找了其他可以在线下载b站视频的网站尝试下载视频也没有成功。

**Comment by zsbai** [comment]
> > 出现
> 
> 我和你的问题是一样的，“视频合成中”之后才显示失败。此外文件夹里只有封面图，没有视频。另外我找了其他可以在线下载b站视频的网站尝试下载视频也没有成功。

我用另一个二进制下载器登陆后是可以下载的，所以应该也不是账号的问题emmmmm

**Comment by blogwy** [comment]
由于我是x86 mac，测试了x86和universal两个安装包。
x86没问题，universal版出现视频合成时候报错。我猜测是universal版本ffmpeg装错了，装成arm架构的了。arm版本我无法测试。
但是之前有[issues](https://github.com/blogwy/BilibiliVideoDownload/issues/57)说可以了，我就没有再关注arm和universal版本。
arm版是我2月28号单独上传的，如果大家是2月28号之前安装的arm版本应该是有问题的，希望大家重新下载3.2.0 arm版本再试一下。
如果还不行，大家暂时就用x86版吧

**Comment by yvonne66999** [comment]
> 由于我是x86 mac，测试了x86和universal两个安装包。 x86没问题，universal版出现视频合成时候报错。我猜测是universal版本ffmpeg装错了，装成arm架构的了。arm版本我无法测试。 但是之前有[issues](https://github.com/blogwy/BilibiliVideoDownload/issues/57)说可以了，我就没有再关注arm和universal版本。 arm版是我2月28号单独上传的，如果大家是2月28号之前安装的arm版本应该是有问题的，希望大家重新下载3.2.0 arm版本再试一下。 如果还不行，大家暂时就用x86版吧

啊我确实用的是universal版的...不知道x86是啥，刚才去下了3.2.0.dmg那个版，已经可以下载视频了。感谢！

**Comment by zsbai** [comment]
> 由于我是x86 mac，测试了x86和universal两个安装包。
> x86没问题，universal版出现视频合成时候报错。我猜测是universal版本ffmpeg装错了，装成arm架构的了。arm版本我无法测试。
> 但是之前有[issues](https://github.com/blogwy/BilibiliVideoDownload/issues/57)说可以了，我就没有再关注arm和universal版本。
> arm版是我2月28号单独上传的，如果大家是2月28号之前安装的arm版本应该是有问题的，希望大家重新下载3.2.0 arm版本再试一下。
> 如果还不行，大家暂时就用x86版吧

看起来确实是这个的问题，我也下载了3.2.0的dmg版本可以正常使用....（话说我怎么记得我之前下的就是这个版本233
不过确实可用了，十分感谢～
