### ISSUE TITLE
能否给任务添加重新开始的右键选项

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [blogwy/BilibiliVideoDownload#67]
有些任务会停在 “正在下载 0%” 的状态不动，重新启动程序也无效，只有手动删除任务并重新添加才能开始下载

**Comment by blogwy** [comment]
下个版本会在下载失败任务添加重试功能

**Comment by blogwy** [comment]
v3.3.0已经在右键菜单添加重新下载选项：https://github.com/blogwy/BilibiliVideoDownload/releases/tag/v3.3.0

**Comment by Misaka-Mikoto-Tech** [comment]
看到了，不错，谢谢
