### ISSUE TITLE
建议在文件名中加入BV号

### ISSUE THREAD

**Issue by xuejianxianzun** [blogwy/BilibiliVideoDownload#68]
现在默认的文件名是视频标题+时间戳，但是没有标记出处信息 ，所以我经常要在下载后修改文件名，加上 up 主名字或者 BV 号。
大佬可以考虑在文件名中添加 up 或者 bv 号吗？这样能省事很多，谢谢！

**Comment by blogwy** [comment]
v3.3.0已发布，https://github.com/blogwy/BilibiliVideoDownload/releases/tag/v3.3.0。下载文件夹/名格式为[px]视频名称-第一up主名称-bv号-uuid

**Comment by xuejianxianzun** [comment]
谢谢大佬！
