### ISSUE TITLE
更新提示弹窗里的按钮没反应

### ISSUE THREAD

**Issue by xuejianxianzun** [blogwy/BilibiliVideoDownload#83]
![20220602_041726.jpg](https://s2.loli.net/2022/06/02/znOXuW3twcHiRQv.jpg)
我今天打开时看到有更新提示，但是不管点哪个按钮都没效果，也无法让这个弹窗消失，只能用任务管理器强制结束。
点击按钮时，按钮有被点击的样式变化，然后会恢复到初始状态。点取消无法取消弹窗，点确定也不会打开更新页面。

版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎1/‎14
操作系统内部版本	19044.1706
体验	Windows Feature Experience Pack 120.2212.4170.0

**Comment by blogwy** [comment]
卸载3.3.1，安装3.3.2，新版本已经修复

**Comment by xuejianxianzun** [comment]
谢谢~
