### ISSUE TITLE
左上角关闭弹窗点击事件不正常

### ISSUE THREAD

**Issue by LiuLiujie** [blogwy/BilibiliVideoDownload#88]
mac arm版3.2.2 版本点击左上角的关闭icon 后会弹窗是否确认关闭，但在弹窗中无论点击`关闭`还是`取消`亦或是键盘点击`esc`键，程序都会关闭

**Comment by zakole0419** [comment]
https://github.com/blogwy/BilibiliVideoDownload/issues/86

**Comment by TheShybin** [comment]
good
